/* Auto-generated by genmsg_cpp for file /home/ssafarik/git/Flyatar2/ros/actuation/flystage/srv/SrvStageState.srv */
#ifndef FLYSTAGE_SERVICE_SRVSTAGESTATE_H
#define FLYSTAGE_SERVICE_SRVSTAGESTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "flystage/MsgFrameState.h"


#include "flystage/MsgFrameState.h"

namespace flystage
{
template <class ContainerAllocator>
struct SrvStageStateRequest_ {
  typedef SrvStageStateRequest_<ContainerAllocator> Type;

  SrvStageStateRequest_()
  : state()
  , velocity(0.0)
  {
  }

  SrvStageStateRequest_(const ContainerAllocator& _alloc)
  : state(_alloc)
  , velocity(0.0)
  {
  }

  typedef  ::flystage::MsgFrameState_<ContainerAllocator>  _state_type;
   ::flystage::MsgFrameState_<ContainerAllocator>  state;

  typedef double _velocity_type;
  double velocity;


private:
  static const char* __s_getDataType_() { return "flystage/SrvStageStateRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "7454f4e3be461aad262545ddd62f41ff"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "5ceca4cecd48a67d8d224ba74f927fbe"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "MsgFrameState state\n\
float64 velocity\n\
\n\
================================================================================\n\
MSG: flystage/MsgFrameState\n\
Header header\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Twist velocity\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, state);
    ros::serialization::serialize(stream, velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, state);
    ros::serialization::deserialize(stream, velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(state);
    size += ros::serialization::serializationLength(velocity);
    return size;
  }

  typedef boost::shared_ptr< ::flystage::SrvStageStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flystage::SrvStageStateRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SrvStageStateRequest
typedef  ::flystage::SrvStageStateRequest_<std::allocator<void> > SrvStageStateRequest;

typedef boost::shared_ptr< ::flystage::SrvStageStateRequest> SrvStageStateRequestPtr;
typedef boost::shared_ptr< ::flystage::SrvStageStateRequest const> SrvStageStateRequestConstPtr;


template <class ContainerAllocator>
struct SrvStageStateResponse_ {
  typedef SrvStageStateResponse_<ContainerAllocator> Type;

  SrvStageStateResponse_()
  : state()
  {
  }

  SrvStageStateResponse_(const ContainerAllocator& _alloc)
  : state(_alloc)
  {
  }

  typedef  ::flystage::MsgFrameState_<ContainerAllocator>  _state_type;
   ::flystage::MsgFrameState_<ContainerAllocator>  state;


private:
  static const char* __s_getDataType_() { return "flystage/SrvStageStateResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1977707d7eabf7e0ca765b9e57161cd5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "5ceca4cecd48a67d8d224ba74f927fbe"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "MsgFrameState state\n\
\n\
\n\
\n\
================================================================================\n\
MSG: flystage/MsgFrameState\n\
Header header\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Twist velocity\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(state);
    return size;
  }

  typedef boost::shared_ptr< ::flystage::SrvStageStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flystage::SrvStageStateResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SrvStageStateResponse
typedef  ::flystage::SrvStageStateResponse_<std::allocator<void> > SrvStageStateResponse;

typedef boost::shared_ptr< ::flystage::SrvStageStateResponse> SrvStageStateResponsePtr;
typedef boost::shared_ptr< ::flystage::SrvStageStateResponse const> SrvStageStateResponseConstPtr;

struct SrvStageState
{

typedef SrvStageStateRequest Request;
typedef SrvStageStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SrvStageState
} // namespace flystage

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::flystage::SrvStageStateRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::flystage::SrvStageStateRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::flystage::SrvStageStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7454f4e3be461aad262545ddd62f41ff";
  }

  static const char* value(const  ::flystage::SrvStageStateRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7454f4e3be461aadULL;
  static const uint64_t static_value2 = 0x262545ddd62f41ffULL;
};

template<class ContainerAllocator>
struct DataType< ::flystage::SrvStageStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "flystage/SrvStageStateRequest";
  }

  static const char* value(const  ::flystage::SrvStageStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::flystage::SrvStageStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "MsgFrameState state\n\
float64 velocity\n\
\n\
================================================================================\n\
MSG: flystage/MsgFrameState\n\
Header header\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Twist velocity\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::flystage::SrvStageStateRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::flystage::SrvStageStateResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::flystage::SrvStageStateResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::flystage::SrvStageStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1977707d7eabf7e0ca765b9e57161cd5";
  }

  static const char* value(const  ::flystage::SrvStageStateResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1977707d7eabf7e0ULL;
  static const uint64_t static_value2 = 0xca765b9e57161cd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::flystage::SrvStageStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "flystage/SrvStageStateResponse";
  }

  static const char* value(const  ::flystage::SrvStageStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::flystage::SrvStageStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "MsgFrameState state\n\
\n\
\n\
\n\
================================================================================\n\
MSG: flystage/MsgFrameState\n\
Header header\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Twist velocity\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::flystage::SrvStageStateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::flystage::SrvStageStateRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SrvStageStateRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::flystage::SrvStageStateResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SrvStageStateResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<flystage::SrvStageState> {
  static const char* value() 
  {
    return "5ceca4cecd48a67d8d224ba74f927fbe";
  }

  static const char* value(const flystage::SrvStageState&) { return value(); } 
};

template<>
struct DataType<flystage::SrvStageState> {
  static const char* value() 
  {
    return "flystage/SrvStageState";
  }

  static const char* value(const flystage::SrvStageState&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<flystage::SrvStageStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5ceca4cecd48a67d8d224ba74f927fbe";
  }

  static const char* value(const flystage::SrvStageStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<flystage::SrvStageStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "flystage/SrvStageState";
  }

  static const char* value(const flystage::SrvStageStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<flystage::SrvStageStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5ceca4cecd48a67d8d224ba74f927fbe";
  }

  static const char* value(const flystage::SrvStageStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<flystage::SrvStageStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "flystage/SrvStageState";
  }

  static const char* value(const flystage::SrvStageStateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // FLYSTAGE_SERVICE_SRVSTAGESTATE_H

