#!/bin/bash

# This script converts bag files to the latest version, and writes the
# converted filename.bag as filename_cnv.bag
# 
# To specify the files to convert, do the following before running:
# export BAGFILESPEC=/asdf/filename*.bag
#

for fn in `ls $BAGFILESPEC | cut -d. -f 1`; do 
    echo $fn.bag
    rosbag fix $fn.bag $fn\_cnv.bag
done

