#!/bin/bash

if [ "$BAGFILESPEC" = "" ]; then 
  echo "BAGFILESPEC is not set.  Use \"export BAGFILESPEC=/path/to/file*.bag\""
else  
  for fn in `ls $BAGFILESPEC`; do
    echo "******************************** Retracking: $fn"
    export BAGFILE=$fn
    RETRACK=1 roslaunch experiments retrack.launch
  done
fi


