(cl:in-package joystick_ps3-msg)
(cl:export '(X_LEFT-VAL
          X_LEFT
          Y_LEFT-VAL
          Y_LEFT
          X_RIGHT-VAL
          X_RIGHT
          Y_RIGHT-VAL
          Y_RIGHT
          UP-VAL
          UP
          DOWN-VAL
          DOWN
          LEFT-VAL
          LEFT
          RIGHT-VAL
          RIGHT
          TRIANGLE-VAL
          TRIANGLE
          X-VAL
          X
          SQUARE-VAL
          SQUARE
          CIRCLE-VAL
          CIRCLE
          SELECT-VAL
          SELECT
          START-VAL
          START
          PLAYSTATION-VAL
          PLAYSTATION
          L1-VAL
          L1
          L2-VAL
          L2
          R1-VAL
          R1
          R2-VAL
          R2
))