/* Auto-generated by genmsg_cpp for file /home/ssafarik/git/Flyatar2/ros/sensing/processing/track_image_contours/msg/Contour.msg */
#ifndef TRACK_IMAGE_CONTOURS_MESSAGE_CONTOUR_H
#define TRACK_IMAGE_CONTOURS_MESSAGE_CONTOUR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace track_image_contours
{
template <class ContainerAllocator>
struct Contour_ {
  typedef Contour_<ContainerAllocator> Type;

  Contour_()
  : header()
  , x(0.0)
  , y(0.0)
  , angle(0.0)
  , area(0.0)
  , ecc(0.0)
  {
  }

  Contour_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , angle(0.0)
  , area(0.0)
  , ecc(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _angle_type;
  double angle;

  typedef double _area_type;
  double area;

  typedef double _ecc_type;
  double ecc;


private:
  static const char* __s_getDataType_() { return "track_image_contours/Contour"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "115e14c56c20d9196c4926428f0b27b5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float64 x\n\
float64 y\n\
float64 angle\n\
float64 area\n\
float64 ecc\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, angle);
    ros::serialization::serialize(stream, area);
    ros::serialization::serialize(stream, ecc);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, angle);
    ros::serialization::deserialize(stream, area);
    ros::serialization::deserialize(stream, ecc);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(angle);
    size += ros::serialization::serializationLength(area);
    size += ros::serialization::serializationLength(ecc);
    return size;
  }

  typedef boost::shared_ptr< ::track_image_contours::Contour_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::track_image_contours::Contour_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Contour
typedef  ::track_image_contours::Contour_<std::allocator<void> > Contour;

typedef boost::shared_ptr< ::track_image_contours::Contour> ContourPtr;
typedef boost::shared_ptr< ::track_image_contours::Contour const> ContourConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::track_image_contours::Contour_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::track_image_contours::Contour_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace track_image_contours

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::track_image_contours::Contour_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::track_image_contours::Contour_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::track_image_contours::Contour_<ContainerAllocator> > {
  static const char* value() 
  {
    return "115e14c56c20d9196c4926428f0b27b5";
  }

  static const char* value(const  ::track_image_contours::Contour_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x115e14c56c20d919ULL;
  static const uint64_t static_value2 = 0x6c4926428f0b27b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::track_image_contours::Contour_<ContainerAllocator> > {
  static const char* value() 
  {
    return "track_image_contours/Contour";
  }

  static const char* value(const  ::track_image_contours::Contour_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::track_image_contours::Contour_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 x\n\
float64 y\n\
float64 angle\n\
float64 area\n\
float64 ecc\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::track_image_contours::Contour_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::track_image_contours::Contour_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::track_image_contours::Contour_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::track_image_contours::Contour_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.angle);
    stream.next(m.area);
    stream.next(m.ecc);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Contour_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::track_image_contours::Contour_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::track_image_contours::Contour_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
    s << indent << "ecc: ";
    Printer<double>::stream(s, indent + "  ", v.ecc);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TRACK_IMAGE_CONTOURS_MESSAGE_CONTOUR_H

