/* Auto-generated by genmsg_cpp for file /home/ssafarik/git/Flyatar/ros/sensing/processing/track_image_contours/msg/ImagePose.msg */
#ifndef TRACK_IMAGE_CONTOURS_MESSAGE_IMAGEPOSE_H
#define TRACK_IMAGE_CONTOURS_MESSAGE_IMAGEPOSE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Pose.h"
#include "geometry_msgs/Pose.h"

namespace track_image_contours
{
template <class ContainerAllocator>
struct ImagePose_ {
  typedef ImagePose_<ContainerAllocator> Type;

  ImagePose_()
  : header()
  , poseRobot()
  , poseFlies()
  {
  }

  ImagePose_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , poseRobot(_alloc)
  , poseFlies(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _poseRobot_type;
   ::geometry_msgs::Pose_<ContainerAllocator>  poseRobot;

  typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poseFlies_type;
  std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  poseFlies;


  ROS_DEPRECATED uint32_t get_poseFlies_size() const { return (uint32_t)poseFlies.size(); }
  ROS_DEPRECATED void set_poseFlies_size(uint32_t size) { poseFlies.resize((size_t)size); }
  ROS_DEPRECATED void get_poseFlies_vec(std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other > & vec) const { vec = this->poseFlies; }
  ROS_DEPRECATED void set_poseFlies_vec(const std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other > & vec) { this->poseFlies = vec; }
private:
  static const char* __s_getDataType_() { return "track_image_contours/ImagePose"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "f1e7088bef29270f52fc2ad60e564399"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
geometry_msgs/Pose poseRobot\n\
geometry_msgs/Pose[] poseFlies\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, poseRobot);
    ros::serialization::serialize(stream, poseFlies);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, poseRobot);
    ros::serialization::deserialize(stream, poseFlies);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(poseRobot);
    size += ros::serialization::serializationLength(poseFlies);
    return size;
  }

  typedef boost::shared_ptr< ::track_image_contours::ImagePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::track_image_contours::ImagePose_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ImagePose
typedef  ::track_image_contours::ImagePose_<std::allocator<void> > ImagePose;

typedef boost::shared_ptr< ::track_image_contours::ImagePose> ImagePosePtr;
typedef boost::shared_ptr< ::track_image_contours::ImagePose const> ImagePoseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::track_image_contours::ImagePose_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::track_image_contours::ImagePose_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace track_image_contours

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::track_image_contours::ImagePose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::track_image_contours::ImagePose_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::track_image_contours::ImagePose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f1e7088bef29270f52fc2ad60e564399";
  }

  static const char* value(const  ::track_image_contours::ImagePose_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf1e7088bef29270fULL;
  static const uint64_t static_value2 = 0x52fc2ad60e564399ULL;
};

template<class ContainerAllocator>
struct DataType< ::track_image_contours::ImagePose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "track_image_contours/ImagePose";
  }

  static const char* value(const  ::track_image_contours::ImagePose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::track_image_contours::ImagePose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/Pose poseRobot\n\
geometry_msgs/Pose[] poseFlies\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::track_image_contours::ImagePose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::track_image_contours::ImagePose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::track_image_contours::ImagePose_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::track_image_contours::ImagePose_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.poseRobot);
    stream.next(m.poseFlies);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ImagePose_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::track_image_contours::ImagePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::track_image_contours::ImagePose_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poseRobot: ";
s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.poseRobot);
    s << indent << "poseFlies[]" << std::endl;
    for (size_t i = 0; i < v.poseFlies.size(); ++i)
    {
      s << indent << "  poseFlies[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poseFlies[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // TRACK_IMAGE_CONTOURS_MESSAGE_IMAGEPOSE_H

