/* Auto-generated by genmsg_cpp for file /home/ssafarik/git/Flyatar/ros/gui/image_gui/msg/CvColor.msg */
#ifndef IMAGE_GUI_MESSAGE_CVCOLOR_H
#define IMAGE_GUI_MESSAGE_CVCOLOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace image_gui
{
template <class ContainerAllocator>
struct CvColor_ {
  typedef CvColor_<ContainerAllocator> Type;

  CvColor_()
  : red(0.0)
  , green(0.0)
  , blue(0.0)
  {
  }

  CvColor_(const ContainerAllocator& _alloc)
  : red(0.0)
  , green(0.0)
  , blue(0.0)
  {
  }

  typedef double _red_type;
  double red;

  typedef double _green_type;
  double green;

  typedef double _blue_type;
  double blue;


private:
  static const char* __s_getDataType_() { return "image_gui/CvColor"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0527f4cbd2a07b7bddf52cf785b45c7c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 red\n\
float64 green\n\
float64 blue\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, red);
    ros::serialization::serialize(stream, green);
    ros::serialization::serialize(stream, blue);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, red);
    ros::serialization::deserialize(stream, green);
    ros::serialization::deserialize(stream, blue);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(red);
    size += ros::serialization::serializationLength(green);
    size += ros::serialization::serializationLength(blue);
    return size;
  }

  typedef boost::shared_ptr< ::image_gui::CvColor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_gui::CvColor_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CvColor
typedef  ::image_gui::CvColor_<std::allocator<void> > CvColor;

typedef boost::shared_ptr< ::image_gui::CvColor> CvColorPtr;
typedef boost::shared_ptr< ::image_gui::CvColor const> CvColorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::image_gui::CvColor_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::image_gui::CvColor_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace image_gui

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::image_gui::CvColor_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::image_gui::CvColor_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::image_gui::CvColor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0527f4cbd2a07b7bddf52cf785b45c7c";
  }

  static const char* value(const  ::image_gui::CvColor_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0527f4cbd2a07b7bULL;
  static const uint64_t static_value2 = 0xddf52cf785b45c7cULL;
};

template<class ContainerAllocator>
struct DataType< ::image_gui::CvColor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "image_gui/CvColor";
  }

  static const char* value(const  ::image_gui::CvColor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::image_gui::CvColor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 red\n\
float64 green\n\
float64 blue\n\
";
  }

  static const char* value(const  ::image_gui::CvColor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::image_gui::CvColor_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::image_gui::CvColor_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.red);
    stream.next(m.green);
    stream.next(m.blue);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CvColor_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_gui::CvColor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::image_gui::CvColor_<ContainerAllocator> & v) 
  {
    s << indent << "red: ";
    Printer<double>::stream(s, indent + "  ", v.red);
    s << indent << "green: ";
    Printer<double>::stream(s, indent + "  ", v.green);
    s << indent << "blue: ";
    Printer<double>::stream(s, indent + "  ", v.blue);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IMAGE_GUI_MESSAGE_CVCOLOR_H

