/* Auto-generated by genmsg_cpp for file /home/ssafarik/git/Flyatar/ros/gui/image_gui/msg/CvSize.msg */
#ifndef IMAGE_GUI_MESSAGE_CVSIZE_H
#define IMAGE_GUI_MESSAGE_CVSIZE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace image_gui
{
template <class ContainerAllocator>
struct CvSize_ {
  typedef CvSize_<ContainerAllocator> Type;

  CvSize_()
  : width(0)
  , height(0)
  {
  }

  CvSize_(const ContainerAllocator& _alloc)
  : width(0)
  , height(0)
  {
  }

  typedef int32_t _width_type;
  int32_t width;

  typedef int32_t _height_type;
  int32_t height;


private:
  static const char* __s_getDataType_() { return "image_gui/CvSize"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a4069c3fe743f7881e847e9b0ab5556a"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 width\n\
int32 height\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, width);
    ros::serialization::serialize(stream, height);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, width);
    ros::serialization::deserialize(stream, height);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(width);
    size += ros::serialization::serializationLength(height);
    return size;
  }

  typedef boost::shared_ptr< ::image_gui::CvSize_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_gui::CvSize_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CvSize
typedef  ::image_gui::CvSize_<std::allocator<void> > CvSize;

typedef boost::shared_ptr< ::image_gui::CvSize> CvSizePtr;
typedef boost::shared_ptr< ::image_gui::CvSize const> CvSizeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::image_gui::CvSize_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::image_gui::CvSize_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace image_gui

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::image_gui::CvSize_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::image_gui::CvSize_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::image_gui::CvSize_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a4069c3fe743f7881e847e9b0ab5556a";
  }

  static const char* value(const  ::image_gui::CvSize_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa4069c3fe743f788ULL;
  static const uint64_t static_value2 = 0x1e847e9b0ab5556aULL;
};

template<class ContainerAllocator>
struct DataType< ::image_gui::CvSize_<ContainerAllocator> > {
  static const char* value() 
  {
    return "image_gui/CvSize";
  }

  static const char* value(const  ::image_gui::CvSize_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::image_gui::CvSize_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 width\n\
int32 height\n\
\n\
";
  }

  static const char* value(const  ::image_gui::CvSize_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::image_gui::CvSize_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::image_gui::CvSize_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.width);
    stream.next(m.height);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CvSize_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_gui::CvSize_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::image_gui::CvSize_<ContainerAllocator> & v) 
  {
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IMAGE_GUI_MESSAGE_CVSIZE_H

