"""autogenerated by genmsg_py from VideoInfo.msg. Do not edit."""
import roslib.message
import struct


class VideoInfo(roslib.message.Message):
  _md5sum = "8b0e55e78ec597bdfc54926b344bac82"
  _type = "save_data/VideoInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool ready_for_bag_info
bool ready_to_record
bool saved_video
"""
  __slots__ = ['ready_for_bag_info','ready_to_record','saved_video']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       ready_for_bag_info,ready_to_record,saved_video
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(VideoInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ready_for_bag_info is None:
        self.ready_for_bag_info = False
      if self.ready_to_record is None:
        self.ready_to_record = False
      if self.saved_video is None:
        self.saved_video = False
    else:
      self.ready_for_bag_info = False
      self.ready_to_record = False
      self.saved_video = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.ready_for_bag_info, _x.ready_to_record, _x.saved_video))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.ready_for_bag_info, _x.ready_to_record, _x.saved_video,) = _struct_3B.unpack(str[start:end])
      self.ready_for_bag_info = bool(self.ready_for_bag_info)
      self.ready_to_record = bool(self.ready_to_record)
      self.saved_video = bool(self.saved_video)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.ready_for_bag_info, _x.ready_to_record, _x.saved_video))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.ready_for_bag_info, _x.ready_to_record, _x.saved_video,) = _struct_3B.unpack(str[start:end])
      self.ready_for_bag_info = bool(self.ready_for_bag_info)
      self.ready_to_record = bool(self.ready_to_record)
      self.saved_video = bool(self.saved_video)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3B = struct.Struct("<3B")
