(cl:defpackage plate_tf-srv
  (:use )
  (:export
   "PLATESTAGECONVERSION"
   "<PLATESTAGECONVERSION-REQUEST>"
   "PLATESTAGECONVERSION-REQUEST"
   "<PLATESTAGECONVERSION-RESPONSE>"
   "PLATESTAGECONVERSION-RESPONSE"
   "PLATECAMERACONVERSION"
   "<PLATECAMERACONVERSION-REQUEST>"
   "PLATECAMERACONVERSION-REQUEST"
   "<PLATECAMERACONVERSION-RESPONSE>"
   "PLATECAMERACONVERSION-RESPONSE"
  ))

