; Auto-generated. Do not edit!


(cl:in-package plate_tf-srv)


;//! \htmlinclude PlateStageConversion-request.msg.html

(cl:defclass <PlateStageConversion-request> (roslisp-msg-protocol:ros-message)
  ((Xsrc
    :reader Xsrc
    :initarg :Xsrc
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (Ysrc
    :reader Ysrc
    :initarg :Ysrc
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass PlateStageConversion-request (<PlateStageConversion-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlateStageConversion-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlateStageConversion-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name plate_tf-srv:<PlateStageConversion-request> is deprecated: use plate_tf-srv:PlateStageConversion-request instead.")))

(cl:ensure-generic-function 'Xsrc-val :lambda-list '(m))
(cl:defmethod Xsrc-val ((m <PlateStageConversion-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader plate_tf-srv:Xsrc-val is deprecated.  Use plate_tf-srv:Xsrc instead.")
  (Xsrc m))

(cl:ensure-generic-function 'Ysrc-val :lambda-list '(m))
(cl:defmethod Ysrc-val ((m <PlateStageConversion-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader plate_tf-srv:Ysrc-val is deprecated.  Use plate_tf-srv:Ysrc instead.")
  (Ysrc m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlateStageConversion-request>) ostream)
  "Serializes a message object of type '<PlateStageConversion-request>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Xsrc))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Xsrc))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Ysrc))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Ysrc))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlateStageConversion-request>) istream)
  "Deserializes a message object of type '<PlateStageConversion-request>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Xsrc) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Xsrc)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Ysrc) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Ysrc)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlateStageConversion-request>)))
  "Returns string type for a service object of type '<PlateStageConversion-request>"
  "plate_tf/PlateStageConversionRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlateStageConversion-request)))
  "Returns string type for a service object of type 'PlateStageConversion-request"
  "plate_tf/PlateStageConversionRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlateStageConversion-request>)))
  "Returns md5sum for a message object of type '<PlateStageConversion-request>"
  "73706dcabefa494de10216f0b3e1c890")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlateStageConversion-request)))
  "Returns md5sum for a message object of type 'PlateStageConversion-request"
  "73706dcabefa494de10216f0b3e1c890")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlateStageConversion-request>)))
  "Returns full string definition for message of type '<PlateStageConversion-request>"
  (cl:format cl:nil "float64[] Xsrc~%float64[] Ysrc~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlateStageConversion-request)))
  "Returns full string definition for message of type 'PlateStageConversion-request"
  (cl:format cl:nil "float64[] Xsrc~%float64[] Ysrc~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlateStageConversion-request>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Xsrc) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Ysrc) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlateStageConversion-request>))
  "Converts a ROS message object to a list"
  (cl:list 'PlateStageConversion-request
    (cl:cons ':Xsrc (Xsrc msg))
    (cl:cons ':Ysrc (Ysrc msg))
))
;//! \htmlinclude PlateStageConversion-response.msg.html

(cl:defclass <PlateStageConversion-response> (roslisp-msg-protocol:ros-message)
  ((Xdst
    :reader Xdst
    :initarg :Xdst
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (Ydst
    :reader Ydst
    :initarg :Ydst
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass PlateStageConversion-response (<PlateStageConversion-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlateStageConversion-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlateStageConversion-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name plate_tf-srv:<PlateStageConversion-response> is deprecated: use plate_tf-srv:PlateStageConversion-response instead.")))

(cl:ensure-generic-function 'Xdst-val :lambda-list '(m))
(cl:defmethod Xdst-val ((m <PlateStageConversion-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader plate_tf-srv:Xdst-val is deprecated.  Use plate_tf-srv:Xdst instead.")
  (Xdst m))

(cl:ensure-generic-function 'Ydst-val :lambda-list '(m))
(cl:defmethod Ydst-val ((m <PlateStageConversion-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader plate_tf-srv:Ydst-val is deprecated.  Use plate_tf-srv:Ydst instead.")
  (Ydst m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlateStageConversion-response>) ostream)
  "Serializes a message object of type '<PlateStageConversion-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Xdst))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Xdst))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Ydst))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Ydst))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlateStageConversion-response>) istream)
  "Deserializes a message object of type '<PlateStageConversion-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Xdst) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Xdst)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Ydst) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Ydst)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlateStageConversion-response>)))
  "Returns string type for a service object of type '<PlateStageConversion-response>"
  "plate_tf/PlateStageConversionResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlateStageConversion-response)))
  "Returns string type for a service object of type 'PlateStageConversion-response"
  "plate_tf/PlateStageConversionResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlateStageConversion-response>)))
  "Returns md5sum for a message object of type '<PlateStageConversion-response>"
  "73706dcabefa494de10216f0b3e1c890")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlateStageConversion-response)))
  "Returns md5sum for a message object of type 'PlateStageConversion-response"
  "73706dcabefa494de10216f0b3e1c890")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlateStageConversion-response>)))
  "Returns full string definition for message of type '<PlateStageConversion-response>"
  (cl:format cl:nil "float64[] Xdst~%float64[] Ydst~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlateStageConversion-response)))
  "Returns full string definition for message of type 'PlateStageConversion-response"
  (cl:format cl:nil "float64[] Xdst~%float64[] Ydst~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlateStageConversion-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Xdst) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Ydst) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlateStageConversion-response>))
  "Converts a ROS message object to a list"
  (cl:list 'PlateStageConversion-response
    (cl:cons ':Xdst (Xdst msg))
    (cl:cons ':Ydst (Ydst msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'PlateStageConversion)))
  'PlateStageConversion-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'PlateStageConversion)))
  'PlateStageConversion-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlateStageConversion)))
  "Returns string type for a service object of type '<PlateStageConversion>"
  "plate_tf/PlateStageConversion")