/* Auto-generated by genmsg_cpp for file /home/ssafarik/git/Flyatar/ros/tf/plate_tf/msg/FlyView.msg */
#ifndef PLATE_TF_MESSAGE_FLYVIEW_H
#define PLATE_TF_MESSAGE_FLYVIEW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace plate_tf
{
template <class ContainerAllocator>
struct FlyView_ {
  typedef FlyView_<ContainerAllocator> Type;

  FlyView_()
  : robot_position_x(0.0)
  , robot_position_y(0.0)
  , robot_angle(0.0)
  , robot_distance(0.0)
  {
  }

  FlyView_(const ContainerAllocator& _alloc)
  : robot_position_x(0.0)
  , robot_position_y(0.0)
  , robot_angle(0.0)
  , robot_distance(0.0)
  {
  }

  typedef double _robot_position_x_type;
  double robot_position_x;

  typedef double _robot_position_y_type;
  double robot_position_y;

  typedef double _robot_angle_type;
  double robot_angle;

  typedef double _robot_distance_type;
  double robot_distance;


private:
  static const char* __s_getDataType_() { return "plate_tf/FlyView"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d3b7acfeacb7f132972aed28543a3ffa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 robot_position_x\n\
float64 robot_position_y\n\
float64 robot_angle\n\
float64 robot_distance\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, robot_position_x);
    ros::serialization::serialize(stream, robot_position_y);
    ros::serialization::serialize(stream, robot_angle);
    ros::serialization::serialize(stream, robot_distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, robot_position_x);
    ros::serialization::deserialize(stream, robot_position_y);
    ros::serialization::deserialize(stream, robot_angle);
    ros::serialization::deserialize(stream, robot_distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(robot_position_x);
    size += ros::serialization::serializationLength(robot_position_y);
    size += ros::serialization::serializationLength(robot_angle);
    size += ros::serialization::serializationLength(robot_distance);
    return size;
  }

  typedef boost::shared_ptr< ::plate_tf::FlyView_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plate_tf::FlyView_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FlyView
typedef  ::plate_tf::FlyView_<std::allocator<void> > FlyView;

typedef boost::shared_ptr< ::plate_tf::FlyView> FlyViewPtr;
typedef boost::shared_ptr< ::plate_tf::FlyView const> FlyViewConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::plate_tf::FlyView_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::plate_tf::FlyView_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace plate_tf

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::plate_tf::FlyView_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::plate_tf::FlyView_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::plate_tf::FlyView_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d3b7acfeacb7f132972aed28543a3ffa";
  }

  static const char* value(const  ::plate_tf::FlyView_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd3b7acfeacb7f132ULL;
  static const uint64_t static_value2 = 0x972aed28543a3ffaULL;
};

template<class ContainerAllocator>
struct DataType< ::plate_tf::FlyView_<ContainerAllocator> > {
  static const char* value() 
  {
    return "plate_tf/FlyView";
  }

  static const char* value(const  ::plate_tf::FlyView_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::plate_tf::FlyView_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 robot_position_x\n\
float64 robot_position_y\n\
float64 robot_angle\n\
float64 robot_distance\n\
\n\
";
  }

  static const char* value(const  ::plate_tf::FlyView_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::plate_tf::FlyView_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::plate_tf::FlyView_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.robot_position_x);
    stream.next(m.robot_position_y);
    stream.next(m.robot_angle);
    stream.next(m.robot_distance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FlyView_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plate_tf::FlyView_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::plate_tf::FlyView_<ContainerAllocator> & v) 
  {
    s << indent << "robot_position_x: ";
    Printer<double>::stream(s, indent + "  ", v.robot_position_x);
    s << indent << "robot_position_y: ";
    Printer<double>::stream(s, indent + "  ", v.robot_position_y);
    s << indent << "robot_angle: ";
    Printer<double>::stream(s, indent + "  ", v.robot_angle);
    s << indent << "robot_distance: ";
    Printer<double>::stream(s, indent + "  ", v.robot_distance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PLATE_TF_MESSAGE_FLYVIEW_H

