"""autogenerated by genpy from galvodirector/MsgGalvoCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import patterngen.msg

class MsgGalvoCommand(genpy.Message):
  _md5sum = "d67d1aac121a314ba47d4fb3bd3c6b7b"
  _type = "galvodirector/MsgGalvoCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool 						enable_laser
patterngen/MsgPattern[] 	pattern_list
string 						units	# 'volts' or 'millimeters'


================================================================================
MSG: patterngen/MsgPattern
string                mode      # 'byshape' or 'bypoints'
string                shape     # 'constant' or 'square' or 'circle' or 'flylogo' or 'spiral' or 'ramp' or 'grid' or 'raster' or 'hilbert' or 'peano' or 'none'
string                frame_id  # The frame to which the pattern applies.
float64               hzPattern # Frequency of the pattern.
float64               hzPoint   # Frequency of points making up the pattern.
int32                 count     # How many times to output the pattern (-1 or N.inf means infinite).
geometry_msgs/Point[] points    # If mode=='bypoints', then this is the list of points to scan.
geometry_msgs/Point   size      # (x,y) dimensions.
bool				  preempt   # Should this message restart an in-progress pattern.
float64               param     # An extra shape-dependent parameter, if needed (hilbert->level, peano->level, spiral->pitch, raster->gridpitch).
 


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['enable_laser','pattern_list','units']
  _slot_types = ['bool','patterngen/MsgPattern[]','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       enable_laser,pattern_list,units

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MsgGalvoCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.enable_laser is None:
        self.enable_laser = False
      if self.pattern_list is None:
        self.pattern_list = []
      if self.units is None:
        self.units = ''
    else:
      self.enable_laser = False
      self.pattern_list = []
      self.units = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.enable_laser))
      length = len(self.pattern_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.pattern_list:
        _x = val1.mode
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.shape
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_2di.pack(_x.hzPattern, _x.hzPoint, _x.count))
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v1 = val1.size
        _x = _v1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_struct_Bd.pack(_x.preempt, _x.param))
      _x = self.units
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pattern_list is None:
        self.pattern_list = None
      end = 0
      start = end
      end += 1
      (self.enable_laser,) = _struct_B.unpack(str[start:end])
      self.enable_laser = bool(self.enable_laser)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pattern_list = []
      for i in range(0, length):
        val1 = patterngen.msg.MsgPattern()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.mode = str[start:end].decode('utf-8')
        else:
          val1.mode = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.shape = str[start:end].decode('utf-8')
        else:
          val1.shape = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _x = val1
        start = end
        end += 20
        (_x.hzPattern, _x.hzPoint, _x.count,) = _struct_2di.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
          val1.points.append(val2)
        _v2 = val1.size
        _x = _v2
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _x = val1
        start = end
        end += 9
        (_x.preempt, _x.param,) = _struct_Bd.unpack(str[start:end])
        val1.preempt = bool(val1.preempt)
        self.pattern_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.units = str[start:end].decode('utf-8')
      else:
        self.units = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.enable_laser))
      length = len(self.pattern_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.pattern_list:
        _x = val1.mode
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.shape
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_2di.pack(_x.hzPattern, _x.hzPoint, _x.count))
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v3 = val1.size
        _x = _v3
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_struct_Bd.pack(_x.preempt, _x.param))
      _x = self.units
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pattern_list is None:
        self.pattern_list = None
      end = 0
      start = end
      end += 1
      (self.enable_laser,) = _struct_B.unpack(str[start:end])
      self.enable_laser = bool(self.enable_laser)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pattern_list = []
      for i in range(0, length):
        val1 = patterngen.msg.MsgPattern()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.mode = str[start:end].decode('utf-8')
        else:
          val1.mode = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.shape = str[start:end].decode('utf-8')
        else:
          val1.shape = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _x = val1
        start = end
        end += 20
        (_x.hzPattern, _x.hzPoint, _x.count,) = _struct_2di.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
          val1.points.append(val2)
        _v4 = val1.size
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _x = val1
        start = end
        end += 9
        (_x.preempt, _x.param,) = _struct_Bd.unpack(str[start:end])
        val1.preempt = bool(val1.preempt)
        self.pattern_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.units = str[start:end].decode('utf-8')
      else:
        self.units = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Bd = struct.Struct("<Bd")
_struct_B = struct.Struct("<B")
_struct_2di = struct.Struct("<2di")
_struct_3d = struct.Struct("<3d")
